import random
lukuX = random.randint(0,9)
lukuY = random.randint(0,9)
lukuZ = random.randint(0,9)
print(f"Ensimmäinen koodi on = {lukuX} {lukuY} {lukuZ}")
lukuA = random.randint(1,6)
lukuB = random.randint(1,6)
lukuC = random.randint(1,6)
lukuD = random.randint(1,6)
print("Toinen koodi on = " , lukuA, lukuB, lukuC, lukuD)